# Character List


nepgear                         ="Character - Nepgear"
IF                              ="Character - IF"
compa                           ="Character - Compa"
uni                             ="Character - Uni"
rom                             ="Character - Rom"
ram                             ="Character - Ram"
red                             ="Character - Red"
broccoli                        ="Character - Broccoli"
fivepb                          ="Character - 5pb."
cave                            ="Character - Cave"
falcom                          ="Character - Falcom"
neptune                         ="Character - Neptune"
noire                           ="Character - Noire"
blanc                           ="Character - Blanc"
vert                            ="Character - Vert"
cyberconnect2                   ="Character - CyberConnect2"
marvy                           ="Character - MarvelousAQL"
tekken                          ="Character - Tekken"
mina                            ="Character - Mina"
kei                             ="Character - Kei"
chika                           ="Character - Chika"
histoire                        ="Character - Histoire"