#Dungeon IDS
DungeonIDs = {
    1: "Virtua Forest",
    2: "Darkness 60",
    3: "Virtua Forest - Depths",
    4: "Rebeat Resort",
    5: "Endless Zone",
    6: "Midcompany",
    7: "Septent Resort",
    8: "Lowee Global Expo - East",
    9: "Lowee Global Expo - West",
    10: "World Labyrinth - 1st Fl.",
    11: "World Labyrinth - 2nd Fl.",
    12: "Gapain Field",
    13: "Underverse",
    14: "Underverse - Depths",
    15: "Severed Dimension",
    16: "Severed Dimension - Depths",
    17: "Iris Field",
    18: "Atari Marsh",
    19: "Atari Marsh - Depths",
    20: "Gamindustri Graveyard",
    21: "Arfoire's Factory",
    22: "LAN Castle",
    23: "LAN Castle - Depths",
    24: "Graveyard Depths",
    25: "LAN Castle - Underground",
    26: "Icicle Pathway",
    27: "Infinite Corridor",
    28: "Junk Box",
    29: "Graveyard - Oblivion",
    30: "Powerlevel Island",
    31: "Panan Jungle",
    32: "Lost Ruins",
    33: "Hellfire Hollow",
    34: "Sublie Road",
    35: "Trinity Marsh",
    36: "Colosseum",
}