from .DungeonNames import *
all_dungeons = {
arfoires_factory: 21,
atari_marsh_depths: 19,
atari_marsh: 18,
darkness_60: 2,
endless_zone: 5,
gamindustri_graveyard: 20,
gapain_field: 12,
graveyard_depths: 24,
graveyard_oblivion: 29,
hellfire_hollow: 33,
icicle_pathway: 26,
infinite_corridor: 27,
iris_field: 17,
junk_box: 28,
lan_castle_depths: 23,
lan_castle_underground: 25,
lan_castle: 22,
lost_ruins: 32,
lowee_global_expo_east: 8,
lowee_global_expo_west: 9,
midcompany: 6,
panan_jungle: 31,
powerlevel_island: 30,
rebeat_resort: 4,
septent_resort: 7,
severed_dimension_depths : 16,
severed_dimension: 15,
sublie_road: 34,
trinity_marsh: 35,
underverse_depths: 14,
underverse: 13,
virtua_forest_depths: 3,
virtua_forest: 1,
world_labyrinth_1st_floor: 10,
world_labyrinth_2nd_floor: 11,
}