nepgear_progressive_gear                    ="Nepgear- Progressive Weapons"
IF_progressive_gear                         ="IF - Progressive Weapons"
compa_progressive_gear                      ="Compa - Progressive Weapons"
uni_progressive_gear                        ="Uni - Progressive Weapons"
rom_progressive_gear                        ="Rom - Progressive Weapons"
ram_progressive_gear                        ="Ram - Progressive Weapons"
red_progressive_gear                        ="Red- Progressive Weapons"
broccoli_progressive_gear                   ="Broccoli - Progressive Weapons"
fivepb_progressive_gear                     ="5pb. - Progressive Weapons"
cave_progressive_gear                       ="Cave - Progressive Weapons"
falcom_progressive_gear                     ="Falcom - Progressive Weapons"
neptune_progressive_gear                    ="Neptune - Progressive Weapons"
noire_progressive_gear                      ="Noire - Progressive Weapons"
blanc_progressive_gear                      ="Blanc- Progressive Weapons"
vert_progressive_gear                       ="Vert - Progressive Weapons"
cyberconnect2_progressive_gear              ="CyberConnect 2 - Progressive Weapons"
marvy_progressive_gear                      ="MarvelousAQL - Progressive Weapons"
tekken_progressive_gear                     ="Tekken- Progressive Weapons"
mina_progressive_gear                       ="Mina - Progressive Weapons"
kei_progressive_gear                        ="Kei - Progressive Weapons"
chika_progressive_gear                      ="Chika - Progressive Weapons"
histoire_progressive_gear                   ="Histoire - Progressive Weapons"
progressive_armor                           ="Progressive Armor"

# All tiers for armor are at 0 anyway