#Dungeons
from .DungeonNames import *
all_dungeons = {
virtua_forest:                   1,
monster_cave:                    2,
west_wind_valley:                3,
thelad_sanctuary:                5,
avenir_storage_no3:              6,
ms_mountain:                     8,
marubaco_forest:                 9,
halo_mountain:                   10,
halo_mountain_peak:              11,
lowee_snowfield:                 12,
avenir_storage_no4:              13,
hyrarule_snowfield:              14,
stella_plains:                   15,
soulsac_cave:                    16,
fantasy_zone:                    17,
neo_geofront:                    18,
neo_geofront_depths:             19,
factory_no459:                   20,
factory_no459_depths:            21,
m_frontier_cave:                 22,
gheytz_forest:                   23,
road_to_celestia:                25,
ms_mountain_peak:                26,
zeca_ruins_no1:                  101,
mechtro_factory:                 102,
ortan_fields:                    103,
toh_kiden_cave:                  104,
gravidaze_ruins:                 106,
gunbreak_underground_cavern:     107,
duty_space:                      109,
donkong_ruins:                   110,
naasne_volcano:                  112,
millenium_labryinth:             113,
kinest_range:                    114,
yukawa_ruins:                    116,
adjiten_forest_pass:             117,
uwii_ruins:                      118,
zeca_ruins_no2:                  120,
dees_snow_forest:                121,
graphic_pass:                    123,
graphic_pass_peak:               124,
naasne_volcano_depths:           128,
#colosseum:                      : 201
}