import typing
from ..LocationData import LocationData
from ..names.DungeonNames import *
Quests: typing.List[LocationData] = (
LocationData([virtua_forest],"[Hunt] Defeating Dogoos", 1, "Quest"),
LocationData([endless_zone],"Seeking Nep Bull", 2, "Quest"),
LocationData([darkness_60],"Idling My Start", 3, "Quest"),
LocationData([virtua_forest, virtua_forest_depths],"Training Regimen", 4, "Quest"),
LocationData([virtua_forest, virtua_forest_depths, darkness_60, rebeat_resort],"I'll Never Stop!", 5, "Quest"),
LocationData([virtua_forest],"[Hunt] Super Strategy - Spa Lord", 6, "Quest"),
LocationData([virtua_forest_depths],"For Her Sake", 7, "Quest"),
LocationData([virtua_forest],"Emergency Hunting Request", 8, "Quest"),
LocationData([darkness_60],"Request from Histy", 9, "Quest"),
LocationData([darkness_60],"Protect Neptune", 10, "Quest"),
LocationData([endless_zone, virtua_forest_depths],"Avenge my Cousin!", 11, "Quest"),
LocationData([panan_jungle],"For Me, Please?", 12, "Quest"),
LocationData([hellfire_hollow],"Blub, Bub", 13, "Quest"),
LocationData([sublie_road],"Schoolgirl Battlers", 14, "Quest"),
LocationData([trinity_marsh],"Jutsu Tools", 15, "Quest"),
LocationData([virtua_forest_depths],"Merry Messy Memorial", 16, "Quest"),
LocationData([virtua_forest_depths, lost_ruins],"Three Kingdoms Lover", 17, "Quest"),
LocationData([virtua_forest_depths],"Assailants", 18, "Quest"),
LocationData([rebeat_resort],"Anannymouse Conspiracy", 19, "Quest"),
LocationData([rebeat_resort],"Please, nya.", 20, "Quest"),
LocationData([virtua_forest_depths],"Bustification Project", 21, "Quest"),
LocationData([rebeat_resort],"CPU Candidate Bust Project", 22, "Quest"),
LocationData([endless_zone],"Gamindustri Invasion!", 23, "Quest"),
LocationData([midcompany, endless_zone],"Anannymouse Hideout", 23, "Quest"),
LocationData([midcompany],"Outburst", 25, "Quest"),
LocationData([septent_resort, underverse_depths],"About Spoilers", 26, "Quest"),
LocationData([rebeat_resort, endless_zone],"Scrubbing Vestiges", 27, "Quest"),
LocationData([septent_resort],"Kuthru Love Stalker", 28, "Quest"),
LocationData([lowee_global_expo_east],"Inappropriate, Perhaps", 29, "Quest"),
LocationData([lowee_global_expo_east],"Lowee Basilicom Request", 30, "Quest"),
LocationData([lowee_global_expo_east],"Eating Alone", 31, "Quest"),
LocationData([lowee_global_expo_west],"Big Boobs, As Wished", 32, "Quest"),
LocationData([lowee_global_expo_west],"Lost Pon-Pon", 33, "Quest"),
LocationData([lowee_global_expo_west],"DSTT Destruction Derby", 34, "Quest"),
LocationData([world_labyrinth_1st_floor],"Invaders From Space", 35, "Quest"),
LocationData([world_labyrinth_1st_floor],"The Day Lowee Stood Still", 36, "Quest"),
LocationData([world_labyrinth_1st_floor],"Gal Can", 37, "Quest"),
LocationData([world_labyrinth_2nd_floor],"[Hunt] No More Summer Breaks!", 38, "Quest"),
LocationData([world_labyrinth_2nd_floor],"[Find] Plum-mets A-Poppin'", 39, "Quest"),
LocationData([world_labyrinth_2nd_floor],"[Find] Bespectacled Wishes", 40, "Quest"),
LocationData([gapain_field],"White Cat Lion", 41, "Quest"),
LocationData([gapain_field],"The Forbidden Beat-up", 42, "Quest"),
LocationData([underverse],"Leanbox SMD", 43, "Quest"),
LocationData([underverse],"Attack of the Ex!", 44, "Quest"),
LocationData([underverse],"On Leanbox Women's Busts", 45, "Quest"),
LocationData([underverse_depths],"In Vert We Trust", 46, "Quest"),
LocationData([underverse_depths],"Ahh! My Dearest Vert!", 47, "Quest"),
LocationData([septent_resort],"God Eaters", 48, "Quest"),
LocationData([lowee_global_expo_west, lowee_global_expo_east, powerlevel_island],"Magical Glacier Wolf", 49, "Quest"),
LocationData([gapain_field],"Slay the Dragon", 50, "Quest"),
LocationData([underverse],"Fiery Mane", 51, "Quest"),
LocationData([midcompany],"Seeking Big Business", 52, "Quest"),
LocationData([world_labyrinth_1st_floor],"A New Challenger!", 53, "Quest"),
LocationData([severed_dimension],"Noisy Band", 54, "Quest"),
LocationData([severed_dimension],"Initial [Y] Occupation", 55, "Quest"),
LocationData([severed_dimension_depths],"Hyahaha! New Frontier!", 56, "Quest"),
LocationData([severed_dimension_depths],"No Forgiveness", 57, "Quest"),
LocationData([iris_field],"Reap the Grassy Field", 58, "Quest"),
LocationData([iris_field],"One Day, One Stipulation", 59, "Quest"),
LocationData([iris_field],"Happy Nue", 60, "Quest"),
LocationData([atari_marsh, atari_marsh_depths],"Danger! Fourlympics", 61, "Quest"),
LocationData([atari_marsh_depths, atari_marsh],"Let Us Cling To Get Her!", 62, "Quest"),
LocationData([atari_marsh_depths],"Doggie Bag", 63, "Quest"),
LocationData([atari_marsh_depths],"Toshiaki's Request", 64, "Quest"),
LocationData([gamindustri_graveyard],"Members Wanted", 65, "Quest"),
LocationData([gamindustri_graveyard],"Masayuki's Dungeon", 66, "Quest"),
LocationData([severed_dimension],"Anti-Social Roar", 67, "Quest"),
LocationData([atari_marsh, gamindustri_graveyard],"Ruler of Dreams", 68, "Quest"),
LocationData([iris_field],"Overprotective?", 69, "Quest"),
LocationData([virtua_forest_depths],"Lastation Crows", 70,2, "Quest"),
LocationData([gamindustri_graveyard],"Smoke Signals of Retaliation", 71, "Quest"),
LocationData([arfoires_factory],"Elephant Man Becomes a Star", 72, "Quest"),
LocationData([arfoires_factory],"Filth Disinfectant!", 73, "Quest"),
LocationData([arfoires_factory],"Harakiri Banzai!", 74, "Quest"),
LocationData([arfoires_factory],"Sunflower Boy", 75, "Quest"),
LocationData([lan_castle],"Narumidrop", 76, "Quest"),
LocationData([lan_castle],"Beyond the Red Door", 77, "Quest"),
LocationData([lan_castle_depths],"Teacher's Melancholy", 78, "Quest"),
LocationData([lan_castle],"Godly Materials Needed!", 79, "Quest"),
LocationData([lan_castle_depths],"Troublesome Company", 80, "Quest"),
LocationData([lan_castle_depths],"Help the Guild", 81, "Quest"),
LocationData([graveyard_depths, lan_castle_underground],"Urgent Quest", 82, "Quest"),
LocationData([arfoires_factory],"Performance Test!", 83,1, "Quest"),
LocationData([graveyard_depths],"Stolen Crown", 84, "Quest"),
LocationData([graveyard_depths],"Spot of the Cow", 85, "Quest"),
LocationData([graveyard_depths],"For Love of the Tome", 86, "Quest"),
LocationData([gapain_field],"Steeeeee-rike!", 87,2, "Quest"),
LocationData([lan_castle_underground],"Nep Fanatic Segregation", 88, "Quest"),
LocationData([lan_castle_underground],"Working at the Basilicom", 89, "Quest"),
LocationData([icicle_pathway],"Lord of Fleas", 90, "Quest"),
LocationData([icicle_pathway],"Inafunasshi!", 91, "Quest"),
LocationData([icicle_pathway],"Looking for Eggs", 92, "Quest"),
LocationData([infinite_corridor],"Moving, nya.", 93, "Quest"),
LocationData([infinite_corridor],"St3D Love Phenomenonring", 94, "Quest"),
LocationData([infinite_corridor],"Last Herb Tale", 95, "Quest"),
LocationData([junk_box],"Shadow Girl Rides a Cloud", 96, "Quest"),
LocationData([junk_box],"HELLCAT Sets Out", 97, "Quest"),
LocationData([junk_box],"Boy's Bathroom Game", 98, "Quest"),
LocationData([junk_box],"Project Blanc", 99, "Quest"),
LocationData([icicle_pathway],"Tale of the Magic Wolf", 100, "Quest"),
LocationData([infinite_corridor],"Hmhm", 101, "Quest"),
LocationData([junk_box],"Removal of Contact Restrictions", 102, "Quest"),
LocationData([septent_resort],"Annoying!", 103,2, "Quest"),
LocationData([world_labyrinth_1st_floor],"Best Salaryman Ever", 104,2, "Quest"),
LocationData([powerlevel_island],"Star Gazer", 105,2, "Quest"),
LocationData([powerlevel_island],"On the Bench", 106,2, "Quest"),
LocationData([gamindustri_graveyard, lan_castle, lan_castle_underground, powerlevel_island],"Land of Origin", 107,2, "Quest"),
LocationData([powerlevel_island],"Brainy Fishman", 108,2, "Quest"),
LocationData([panan_jungle],"Talk of the Century", 109, "Quest"),
LocationData([midcompany, panan_jungle, lan_castle, lan_castle_underground, junk_box],"Planeptune Restoration", 110, "Quest"),
LocationData([panan_jungle],"All Eyes on Her", 111, "Quest"),
LocationData([panan_jungle],"A Beautiful Legend's Origin", 112, "Quest"),
)
